[package]
name = "advent_2022"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = "0.11"
phf_macros = "0.11"
chrono = "0.4.23"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
